# Generated by Django 4.2.1 on 2023-05-18 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=3)),
                ('photo', models.CharField(max_length=400)),
                ('spotify_link', models.CharField(max_length=200)),
                ('biography', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('views', models.IntegerField(default=0)),
                ('photo', models.CharField(max_length=40)),
                ('lengths', models.CharField(max_length=40)),
                ('lyrics', models.CharField(max_length=10000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.author')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_Name', models.CharField(max_length=40)),
                ('views', models.IntegerField(default=0)),
                ('photo', models.CharField(max_length=200)),
                ('spotify_link', models.CharField(max_length=200)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.author')),
                ('songs', models.ManyToManyField(to='song.song')),
            ],
        ),
    ]
