# Generated by Django 4.2.1 on 2023-05-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_song_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(max_length=10000),
        ),
    ]
