# Generated by Django 4.2.1 on 2023-05-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_song_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='spotify',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
